
name: CI

on:
  push:
    branches: [ "v2" ] 
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push docker image
        with:
          image: sanudutta/mydrive_gui
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}